# -*- coding: utf-8 -*-
"""Emotion_Detection_final_Project_Cv (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17G5hwIQskG2wtfhHXwinS2aN-8QXg0vJ
"""

from google.colab import files
uploaded = files.upload()

import zipfile
import os

zip_file_name = list(uploaded.keys())[0]

extract_path = "/content/emotion_data"

with zipfile.ZipFile(zip_file_name, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted successfully")

#paths of train and test data
train_dir = "/content/emotion_data/train"
test_dir = "/content/emotion_data/test"

!pip install -q tensorflow opencv-python matplotlib scikit-learn pandas joblib

import os
import zipfile
import json
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

from google.colab import files
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import (
    Input,
    Rescaling,
    RandomFlip,
    RandomRotation,
    RandomZoom,
    Conv2D,
    MaxPooling2D,
    BatchNormalization,
    Flatten,
    Dense,
    Dropout
)
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

def find_train_test_dirs(base_path):
    train_dir = None
    test_dir = None

    for root, dirs, files_in_dir in os.walk(base_path):
        lower_dirs = [d.lower() for d in dirs]

        if "train" in lower_dirs:
            train_dir = os.path.join(root, dirs[lower_dirs.index("train")])

        if "test" in lower_dirs:
            test_dir = os.path.join(root, dirs[lower_dirs.index("test")])

    return train_dir, test_dir


train_dir, test_dir = find_train_test_dirs(extract_path)

print("Train directory:", train_dir)
print("Test directory:", test_dir)

if train_dir is None or test_dir is None:
    raise ValueError("Train or test folder not found. Make sure your dataset has train and test folders.")

class_folders = sorted(os.listdir(train_dir))

print("Emotion classes found:")
for class_name in class_folders:
    class_path = os.path.join(train_dir, class_name)
    if os.path.isdir(class_path):
        print(class_name, ":", len(os.listdir(class_path)), "images")

IMG_SIZE = (48, 48)
BATCH_SIZE = 32

train_dataset = tf.keras.preprocessing.image_dataset_from_directory(
    train_dir,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    color_mode="grayscale",
    label_mode="int",
    shuffle=True
)

test_dataset = tf.keras.preprocessing.image_dataset_from_directory(
    test_dir,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    color_mode="grayscale",
    label_mode="int",
    shuffle=False
)

class_names = train_dataset.class_names
num_classes = len(class_names)

print("Class names:", class_names)
print("Number of classes:", num_classes)

AUTOTUNE = tf.data.AUTOTUNE

train_dataset = train_dataset.prefetch(buffer_size=AUTOTUNE)
test_dataset = test_dataset.prefetch(buffer_size=AUTOTUNE)

plt.figure(figsize=(10, 10))

for images, labels in train_dataset.take(1):
    for i in range(9):
        plt.subplot(3, 3, i + 1)
        plt.imshow(images[i].numpy().astype("uint8").squeeze(), cmap="gray")
        plt.title(class_names[labels[i]])
        plt.axis("off")

plt.show()

model = Sequential([
    Input(shape=(48, 48, 1)),

    # Correct normalization: 0–255 to 0–1
    Rescaling(1./255),

    # Useful data augmentation
    RandomFlip("horizontal"),
    RandomRotation(0.08),
    RandomZoom(0.08),

    Conv2D(32, (3, 3), activation="relu", padding="same"),
    BatchNormalization(),
    MaxPooling2D((2, 2)),

    Conv2D(64, (3, 3), activation="relu", padding="same"),
    BatchNormalization(),
    MaxPooling2D((2, 2)),

    Conv2D(128, (3, 3), activation="relu", padding="same"),
    BatchNormalization(),
    MaxPooling2D((2, 2)),

    Flatten(),

    Dense(128, activation="relu"),
    Dropout(0.4),

    Dense(num_classes, activation="softmax")
])

model.summary()

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

early_stop = EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)

checkpoint = ModelCheckpoint(
    "best_emotion_model.keras",
    monitor="val_accuracy",
    save_best_only=True,
    mode="max",
    verbose=1
)

EPOCHS = 25

history = model.fit(
    train_dataset,
    validation_data=test_dataset,
    epochs=EPOCHS,
    callbacks=[early_stop, checkpoint]
)

test_loss, test_accuracy = model.evaluate(test_dataset)

print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

y_true = []
y_pred = []

for images, labels in test_dataset:
    predictions = model.predict(images, verbose=0)
    predicted_labels = np.argmax(predictions, axis=1)

    y_true.extend(labels.numpy())
    y_pred.extend(predicted_labels)

y_true = np.array(y_true)
y_pred = np.array(y_pred)

print("Classification Report:")
print(classification_report(y_true, y_pred, target_names=class_names))

model.save("final_emotion_detection_model.keras")

with open("class_names.json", "w") as f:
    json.dump(class_names, f)

print("Model and class names saved successfully.")

loaded_model = load_model("final_emotion_detection_model.keras")

with open("class_names.json", "r") as f:
    loaded_class_names = json.load(f)

print("Loaded model successfully.")
print("Loaded classes:", loaded_class_names)

def preprocess_image_with_face_detection(image_path):
    image_bgr = cv2.imread(image_path)

    if image_bgr is None:
        raise ValueError("Image not found. Please check the image path.")

    gray = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)

    face_cascade = cv2.CascadeClassifier(
        cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
    )

    faces = face_cascade.detectMultiScale(
        gray,
        scaleFactor=1.3,
        minNeighbors=5
    )

    if len(faces) > 0:
        x, y, w, h = faces[0]
        face = gray[y:y+h, x:x+w]
    else:
        face = gray

    face_resized = cv2.resize(face, (48, 48))

    input_image = face_resized.astype("float32")
    input_image = np.expand_dims(input_image, axis=0)
    input_image = np.expand_dims(input_image, axis=-1)

    return image_bgr, face_resized, input_image

def predict_emotion(image_path):
    original_image, face_image, input_image = preprocess_image_with_face_detection(image_path)

    probabilities = loaded_model.predict(input_image, verbose=0)[0]

    predicted_index = np.argmax(probabilities)
    predicted_emotion = loaded_class_names[predicted_index]
    confidence = probabilities[predicted_index] * 100

    plt.figure(figsize=(4, 4))
    plt.imshow(face_image, cmap="gray")
    plt.title(f"Predicted Emotion: {predicted_emotion}\nConfidence: {confidence:.2f}%")
    plt.axis("off")
    plt.show()

    result_df = pd.DataFrame({
        "Emotion": loaded_class_names,
        "Probability": probabilities
    })

    return predicted_emotion, confidence, result_df

uploaded_image = files.upload()

test_image_path = list(uploaded_image.keys())[0]

predicted_emotion, confidence, result_df = predict_emotion(test_image_path)

print("Predicted Emotion:", predicted_emotion)
print("Confidence:", round(confidence, 2), "%")

result_df

plt.figure(figsize=(8, 5))
plt.bar(result_df["Emotion"], result_df["Probability"])
plt.title("Emotion Prediction Probability")
plt.xlabel("Emotion")
plt.ylabel("Probability")
plt.xticks(rotation=45)
plt.ylim(0, 1)
plt.grid(axis="y")
plt.show()

files.download("final_emotion_detection_model.keras")
files.download("class_names.json")

uploaded_image = files.upload()

test_image_path = list(uploaded_image.keys())[0]

predicted_emotion, confidence, result_df = predict_emotion(test_image_path)

print("Predicted Emotion:", predicted_emotion)
print("Confidence:", round(confidence, 2), "%")

result_df

